# Generated by Django 5.0.1 on 2024-05-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=20)),
                ('bar_data', models.TextField(max_length=40)),
                ('item_img', models.ImageField(default=None, max_length=300, null=True, upload_to='item_img/')),
            ],
        ),
    ]
