# Generated by Django 5.0.1 on 2024-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
