# Generated by Django 5.0.1 on 2024-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_data', '0002_itemdata_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='me', max_length=10)),
                ('scanned_item', models.TextField(max_length=20)),
                ('in_cart', models.BooleanField(default=False)),
            ],
        ),
    ]
